services:
  mysql:
    image: mysql:8.4
    restart: always
    container_name: mysql-eventlinker
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports: 
      - '3336:3306'
    networks: 
      - eventlinker-network
    volumes:
      - ../db/db_events.sql:/docker-entrypoint-initdb.d/db_events.sql
networks:
  eventlinker-network:
    driver: bridge